name: sociogram
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.1.0
  intl_phone_number_field: ^0.1.7
  otp_text_field: ^1.1.3
  calendar_date_picker2: ^0.5.5
  get_cli: ^1.8.1
  get:
  image_picker: ^1.0.7
  syncfusion_flutter_charts: ^25.1.38
  flutter_rating_bar: ^4.0.1
  getwidget: ^4.0.0
  story_view: ^0.16.0
  url_launcher_windows: ^3.1.1
  flutter_share: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Urbanist
      fonts:
        - asset: asset/Urbanist-Black.ttf
    - family: Urbanist-medium
      fonts:
        - asset: asset/Urbanist-Medium.ttf
    - family: Urbanist-semibold
      fonts:
        - asset: asset/Urbanist-SemiBold.ttf
    - family: Urbanist-bold
      fonts:
        - asset: asset/Urbanist-Bold.ttf
    - family: Urbanist-regular
      fonts:
        - asset: asset/Urbanist-Regular.ttf
